/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:40 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NFPowerObserverDelegate, OS_dispatch_queue;
#import <libnfshared.dylib/libnfshared.dylib-Structs.h>
@class NSObject;

@interface NFPowerObserver : NSObject {

	id<NFPowerObserverDelegate> _delegate;
	unsigned _powerNotificationConnection;
	IONotificationPortRef _powerNotificationPort;
	unsigned _powerNotificationNotifier;
	NSObject*<OS_dispatch_queue> _workQueue;
	void* _sleepMessageArgument;
	BOOL _willSleep;

}

@property (readonly) BOOL willSleep;              //@synthesize willSleep=_willSleep - In the implementation block
-(BOOL)willSleep;
-(void)dealloc;
-(id)initWithDelegate:(id)arg1 ;
-(void)unregisterForEvents;
-(BOOL)isPluggedIntoPower;
-(BOOL)registerForEvents;
-(void)allowSleep;
-(id)delegate;
-(void)_powerNotificationMessage:(unsigned)arg1 argument:(void*)arg2 ;
@end

