/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:40 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_os_transaction;
#import <libnfshared.dylib/libnfshared.dylib-Structs.h>
@class NSMutableDictionary, NSObject;

@interface NFPowerAssertion : NSObject {

	unsigned _powerNotificationConnection;
	IONotificationPortRef _powerNotificationPort;
	unsigned _powerNotificationNotifier;
	unsigned _assertionID;
	NSMutableDictionary* _assertionHolders;
	NSObject*<OS_dispatch_queue> _queue;
	NSObject*<OS_os_transaction> _powerAssertTransaction;
	BOOL _enableDebug;

}

@property (assign,nonatomic) BOOL enableDebug;              //@synthesize enableDebug=_enableDebug - In the implementation block
+(id)sharedPowerAssertion;
-(id)init;
-(BOOL)enableDebug;
-(id)assertionHolders;
-(id)dumpState;
-(void)setEnableDebug:(BOOL)arg1 ;
-(void)holdPowerAssertion:(id)arg1 ;
-(void)releasePowerAssertion:(id)arg1 ;
@end

