/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:40 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSData;

@interface NFResponseAPDU : NSObject {

	unsigned short _status;
	NSData* _data;

}

@property (nonatomic,readonly) unsigned short status;              //@synthesize status=_status - In the implementation block
@property (nonatomic,readonly) NSData * response; 
@property (nonatomic,readonly) NSData * data;                      //@synthesize data=_data - In the implementation block
+(id)responseWithData:(id)arg1 ;
-(NSData *)data;
-(NSData *)response;
-(unsigned short)status;
-(unsigned short)decodeUnderlyingAppletError:(id*)arg1 ;
-(id)initWithData:(id)arg1 ;
@end

