/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:40 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_xpc_object;
@class NSString, NSObject;

@interface NFSecureXPCEventPublisher : NSObject {

	BOOL _available;
	NSString* _serviceName;
	NSObject*<OS_dispatch_queue> _queue;
	NSObject*<OS_xpc_object> _connection;

}

@property (nonatomic,retain) NSString * serviceName;                           //@synthesize serviceName=_serviceName - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;               //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) NSObject*<OS_xpc_object> connection;              //@synthesize connection=_connection - In the implementation block
@property (assign,nonatomic) BOOL available;                                   //@synthesize available=_available - In the implementation block
-(BOOL)available;
-(void)setAvailable:(BOOL)arg1 ;
-(void)setServiceName:(NSString *)arg1 ;
-(NSString *)serviceName;
-(void)dealloc;
-(void)setConnection:(NSObject*<OS_xpc_object>)arg1 ;
-(void)sendEvent:(id)arg1 ;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(NSObject*<OS_xpc_object>)connection;
-(id)initWithMachPort:(id)arg1 queue:(id)arg2 ;
-(void)sendSimpleEvent:(id)arg1 ;
-(void)sendSimpleEvent:(id)arg1 objectString:(id)arg2 ;
-(void)sendSimpleEvent:(id)arg1 objectNumber:(id)arg2 ;
@end

