/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:43 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAudioStatistics.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSXPCConnection, NSMutableDictionary;

@interface CAReportingClient : NSObject {

	NSXPCConnection* _connection;
	NSMutableDictionary* _clientReporters;

}

@property (retain) NSXPCConnection * connection;                       //@synthesize connection=_connection - In the implementation block
@property (retain) NSMutableDictionary * clientReporters;              //@synthesize clientReporters=_clientReporters - In the implementation block
+(id)sharedInstance;
+(id)getClient;
+(void)destroyClient;
-(void)destroyReporterWithID:(long long)arg1 ;
-(NSMutableDictionary *)clientReporters;
-(void)sendMessage:(id)arg1 category:(unsigned)arg2 type:(unsigned short)arg3 reporters:(id)arg4 ;
-(void)setServiceType:(unsigned short)arg1 reporterID:(long long)arg2 ;
-(unsigned short)getServiceTypeForReporterID:(long long)arg1 ;
-(void)setConfiguration:(id)arg1 reporterID:(long long)arg2 ;
-(void)setConnection:(NSXPCConnection *)arg1 ;
-(id)initWithXPC:(BOOL)arg1 endpoint:(id)arg2 ;
-(id)listClientReporterIDs;
-(id)getConfigurationForReporterID:(long long)arg1 ;
-(long long)createReporterID:(unsigned)arg1 ;
-(void)disconnectReporters;
-(id)listServerReporterIDs;
-(void)stopReporters:(id)arg1 ;
-(void)reconnectReporters;
-(void)destoryService;
-(void)reconnectReporter:(id)arg1 ;
-(void)setClientReporters:(NSMutableDictionary *)arg1 ;
-(id)reporterWithID:(long long)arg1 ;
-(void)startReporters:(id)arg1 ;
-(NSXPCConnection *)connection;
-(void)addReporter:(id)arg1 ;
@end

