/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:55:16 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libboringssl.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/OS_boringssl_session_state.h>

@class NSString;

@interface boringssl_concrete_boringssl_session_state : NSObject <OS_boringssl_session_state> {

	unsigned char used_extended_master_secret;
	sockaddr_in_4_6 remote_address;
	char* serialized_session;
	unsigned long long serialized_session_length;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
@end

