/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:48 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/swift/libswiftCoreAudio.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _TtCV9CoreAudio25ManagedAudioChannelLayoutP33_429D68E17F2C221C283DB52CAE70232C7Storage : _UKNOWN_SUPERCLASS_ {

	 audioChannelLayoutPointer;
	 deallocator;

}
@end

