/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:48 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/swift/libswiftCoreNFC.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NFCTagReaderSessionDelegate <NSObject>
@optional
-(void)tagReaderSessionDidBecomeActive:(id)arg1;
-(void)tagReaderSession:(id)arg1 didDetectTags:(id)arg2;

@required
-(void)tagReaderSession:(id)arg1 didInvalidateWithError:(id)arg2;

@end

