/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:57:43 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, NSUserDefaults, NSDictionary, NSMutableDictionary;

@interface AppletConfigurationData : NSObject {

	NSObject*<OS_dispatch_queue> queue;
	NSUserDefaults* userDefaults;
	NSDictionary* config;
	NSMutableDictionary* pluginCache;
	unsigned long long maErrorCount;
	BOOL retryInProgress;
	double maMetadataQueryInterval;

}
+(void)init;
+(id)getWuluSettings;
+(id)extraDebugScriptForModule:(id)arg1 ;
+(id)getNFCSettings;
+(id)pluginDecoderForMid:(id)arg1 ;
+(id)getHerculesSettings;
+(id)plasticCardScriptForModule:(id)arg1 ;
+(id)scriptForModule:(id)arg1 ;
+(id)getStaticConfig;
+(id)dataHash;
+(id)getExpressModeSettings;
-(id)init;
-(void)tsmScriptPerformed:(id)arg1 ;
@end

