/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:57:43 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_source, OS_dispatch_queue;
@class NSObject;

@interface ATLTimer : NSObject {

	NSObject*<OS_dispatch_source> _src;
	/*^block*/id _block;
	double _delay;
	NSObject*<OS_dispatch_queue> _queue;

}
-(void)dealloc;
@end

