/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:57:43 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAppletTranslationLibrary.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface HerculesFareTables : NSObject
+(unsigned)getProductIDWithTicketType:(unsigned char)arg1 withOperatorID:(unsigned char)arg2 withRiderClass:(unsigned char)arg3 forCity:(id)arg4 withProductCategory:(char*)arg5 withError:(id*)arg6 ;
@end

