/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:43 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libFusionComponentCheck.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface HSComponentCheck : NSObject {

	unsigned long long currentContext;

}
+(void)setContext:(unsigned long long)arg1 ;
+(unsigned long long)getContext;
+(id)sharedSingleton;
-(id)init;
-(id)createChallenge;
-(id)generateSignedKETS:(id)arg1 status:(id)arg2 errorStr:(id)arg3 ;
-(id)calculateSHA512:(id)arg1 ;
-(int)processComponentCheckCommand:(id)arg1 response:(id*)arg2 ;
@end

