/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:46 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libauthinstall.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NSURLConnectionDataDelegate <NSURLConnectionDelegate>
@optional
-(void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
-(id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
-(void)connectionDidFinishLoading:(id)arg1;
-(id)connection:(id)arg1 needNewBodyStream:(id)arg2;
-(id)connection:(id)arg1 willCacheResponse:(id)arg2;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2;
-(void)connection:(id)arg1 didReceiveData:(id)arg2;

@end

