/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:52:00 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface __SwiftValue : NSObject <NSCopying>
+(id)allocWithZone:(NSZone*)arg1 ;
-(const OpaqueValueRef)_swiftValue;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)dealloc;
-(unsigned long long)hash;
-(id)description;
-(BOOL)isEqual:(id)arg1 ;
-(const TargetMetadata<swift::InProcess>*)_swiftTypeMetadata;
-(id)_swiftTypeName;
-(id)debugDescription;
@end

