/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:03:16 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct _cxx_atomic_impl<swift::RefCountBitsT<swift::RefCountIsInline>, std::__1::__cxx_atomic_base_impl<swift::RefCountBitsT<swift::RefCountIsInline> > > {
	ARefCountBitsT<swift::RefCountIsInline> __a_value;
} cxx_atomic_impl<swift::RefCountBitsT<swift::RefCountIsInline>, std::__1::__cxx_atomic_base_impl<swift::RefCountBitsT<swift::RefCountIsInline> > >;

typedef struct atomic<swift::RefCountBitsT<swift::RefCountIsInline> > {
	cxx_atomic_impl<swift::RefCountBitsT<swift::RefCountIsInline>, std::__1::__cxx_atomic_base_impl<swift::RefCountBitsT<swift::RefCountIsInline> > > __a_;
} atomic<swift::RefCountBitsT<swift::RefCountIsInline> >;

typedef struct RefCounts<swift::RefCountBitsT<swift::RefCountIsInline> > {
	atomic<swift::RefCountBitsT<swift::RefCountIsInline> > refCounts;
} RefCounts<swift::RefCountBitsT<swift::RefCountIsInline> >;

