/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:52:00 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <libswiftCore.dylib/Swift.__SwiftNativeNSEnumerator.h>
#import <libobjc.A.dylib/Swift._NSEnumerator.h>

@interface Swift.__SwiftEmptyNSEnumerator : Swift.__SwiftNativeNSEnumerator <Swift._NSEnumerator>
-(id)nextObject;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(long long)countByEnumeratingWithState:(SCD_Struct_Sw0*)arg1 objects:(id*)arg2 count:(long long)arg3 ;
@end

