/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:52:00 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/swift/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/__SwiftNativeNSDictionaryBase.h>

@interface Swift.__SwiftNativeNSDictionary : __SwiftNativeNSDictionaryBase
-(id)initWithCoder:(id)arg1 ;
@end

