/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:44 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libPPMDataModel.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct {
	float list;
	unsigned long long count;
	unsigned long long size;
} SCD_Struct_OT1;

typedef struct {
	unsigned baselineWRdc : 1;
	unsigned mLBConfig : 1;
	unsigned maxRdcRatio : 1;
	unsigned maxRdcRatioR2Extrap : 1;
	unsigned wRdcRatioThresh : 1;
} SCD_Struct_OT2;

