/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:48 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/swift/libswiftAppleArchive.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _TtCC12AppleArchive13ArchiveStreamP33_4438800270C24D4D260353A75D774C7225CustomArchiveStreamBridge : _UKNOWN_SUPERCLASS_ {

	 instance;
	 yaaStream;

}
@end

