/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:45 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ACC2SVTransportControllerProtocol <NSObject>
@optional
-(void)getImageWithURL:(id)arg1 completion:(/*^block*/id)arg2;
-(void)cancelImageFetching;
-(void)verifyRecoveryKeyWithContext:(id)arg1 completion:(/*^block*/id)arg2;
-(void)validateServiceTicketWithContext:(id)arg1 completion:(/*^block*/id)arg2;

@required
-(void)generateAndSendSecCodeWithContext:(id)arg1 completion:(/*^block*/id)arg2;
-(void)verifySecureCodeWithContext:(id)arg1 completion:(/*^block*/id)arg2;
-(void)loadTrustedDevicesWithContext:(id)arg1 completion:(/*^block*/id)arg2;

@end

