/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:45 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIViewController.h>

@class NSString;

@interface ACMDialog : UIViewController {

	long long _savedStatusBarStyle;

}

@property (readonly) long long statusBarStyle; 
@property (assign) long long savedStatusBarStyle;                 //@synthesize savedStatusBarStyle=_savedStatusBarStyle - In the implementation block
@property (readonly) NSString * backgroundImageName; 
+(id)dialog;
-(void)applicationWillEnterForeground;
-(void)applicationWillResignActive;
-(void)applicationDidEnterBackground;
-(void)applicationDidBecomeActive;
-(id)init;
-(void)dealloc;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(long long)statusBarStyle;
-(void)viewWillAppear:(BOOL)arg1 ;
-(long long)modalTransitionStyle;
-(void)viewDidAppear:(BOOL)arg1 ;
-(NSString *)backgroundImageName;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)loadView;
-(void)setSavedStatusBarStyle:(long long)arg1 ;
-(long long)savedStatusBarStyle;
-(void)disableControls:(BOOL)arg1 ;
-(void)showWithParentViewController:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(void)hideWithParentViewController:(id)arg1 animated:(BOOL)arg2 completion:(/*^block*/id)arg3 ;
-(BOOL)shouldManuallyChangeStatusBarStyle;
@end

