/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:45 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ACMExternalAppleConnectPrivate <ACMExternalAppleConnect>
@property (assign) id masterObject; 
@required
-(id)masterObject;
-(void)setMasterObject:(id)arg1;
-(BOOL)shouldReleaseOnMemoryWarning;

@end

