/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:45 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class UIImage, UIColor, NSString;


@protocol ACMSignInDialogSimpleProtocol <ACMSignInDialogProtocol>
@property (nonatomic,retain) UIImage * logo; 
@property (nonatomic,retain) UIColor * backgroundColor; 
@property (nonatomic,retain) NSString * accountNameFieldPlaceholder; 
@required
-(void)setBackgroundColor:(id)arg1;
-(void)setLogo:(id)arg1;
-(UIImage *)logo;
-(UIColor *)backgroundColor;
-(void)setAccountNameFieldPlaceholder:(id)arg1;
-(NSString *)accountNameFieldPlaceholder;

@end

