/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:52:00 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/swift/libswiftFoundation.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftFoundation.dylib/libswiftFoundation.dylib-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface _TtCC10FoundationP33_6DA0945A07226B3278459E9368612FF427__KVOKeyPathBridgeMachinery9BridgeKey : NSObject <NSCopying> {

	 value;

}

@property (readonly,nonatomic) long long hash; 
-(id)init;
-(id)copyWithZone:(void*)arg1 ;
-(long long)hash;
-(BOOL)isEqual:(id)arg1 ;
@end

