/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:52:00 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/swift/libswiftFoundation.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _TtCE10FoundationCSo7NSTimer14TimerPublisher : _UKNOWN_SUPERCLASS_ {

	 interval;
	 tolerance;
	 runLoop;
	 mode;
	 options;
	 sides;
	 lock;

}
@end

