/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:52:00 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/swift/libswiftFoundation.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@interface _TtCE10FoundationCSo16NSOperationQueueP33_0ECEE0A75E2DD5EDFED9A6FEB26D5D3219DelayReadyOperation : NSOperation {

	 action;
	 readyFromAfter;
	 queue;
	 interval;
	 context;

}

@property (readonly,nonatomic) BOOL ready; 
-(BOOL)isReady;
-(id)init;
-(void)main;
-(void)cancel;
@end

