/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:34 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTAuthorizationManager.h>

@interface RTAuthorizationManager_Embedded : RTAuthorizationManager
-(id)initWithMetricManager:(id)arg1 platform:(id)arg2 userSessionMonitor:(id)arg3 ;
-(BOOL)isLocationServicesEnabled;
@end

