/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:33 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class Protocol, NSDictionary;

@interface RTEntitlementProvider : NSObject {

	Protocol* _protocol;
	NSDictionary* _entitlementsDictionary;

}

@property (nonatomic,retain) NSDictionary * entitlementsDictionary;              //@synthesize entitlementsDictionary=_entitlementsDictionary - In the implementation block
@property (nonatomic,readonly) Protocol * protocol;                              //@synthesize protocol=_protocol - In the implementation block
+(id)internalDaemonProtocolEntitlementProvider;
+(id)helperServiceProtocolEntitlementProvider;
+(id)selectorsForProtocol:(id)arg1 ;
+(id)daemonProtocolEntitlementProvider;
-(id)init;
-(Protocol *)protocol;
-(NSDictionary *)entitlementsDictionary;
-(void)setEntitlementsDictionary:(NSDictionary *)arg1 ;
-(BOOL)clientConnection:(id)arg1 hasEntitlement:(id)arg2 ;
-(BOOL)clientConnection:(id)arg1 satisfiesEntitlementRequirementsForInvocation:(id)arg2 ;
-(id)initWithProtocol:(id)arg1 entitlementsDictionary:(id)arg2 ;
@end

