/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:33 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate;

@interface RTFMCScoreBoard : NSObject {

	BOOL _engaged;
	BOOL _assisted;
	int _locationType;
	int _parkingEvents;
	int _engagedParkingEvents;
	int _assistedParkingEvents;
	int _engagements;
	int _assistances;
	int _suppressedEvents;
	NSDate* _creationDate;

}

@property (nonatomic,retain) NSDate * creationDate;                  //@synthesize creationDate=_creationDate - In the implementation block
@property (assign,nonatomic) int locationType;                       //@synthesize locationType=_locationType - In the implementation block
@property (assign,nonatomic) BOOL engaged;                           //@synthesize engaged=_engaged - In the implementation block
@property (assign,nonatomic) BOOL assisted;                          //@synthesize assisted=_assisted - In the implementation block
@property (assign,nonatomic) int parkingEvents;                      //@synthesize parkingEvents=_parkingEvents - In the implementation block
@property (assign,nonatomic) int engagedParkingEvents;               //@synthesize engagedParkingEvents=_engagedParkingEvents - In the implementation block
@property (assign,nonatomic) int assistedParkingEvents;              //@synthesize assistedParkingEvents=_assistedParkingEvents - In the implementation block
@property (assign,nonatomic) int engagements;                        //@synthesize engagements=_engagements - In the implementation block
@property (assign,nonatomic) int assistances;                        //@synthesize assistances=_assistances - In the implementation block
@property (assign,nonatomic) int suppressedEvents;                   //@synthesize suppressedEvents=_suppressedEvents - In the implementation block
-(NSDate *)creationDate;
-(void)setLocationType:(int)arg1 ;
-(void)setCreationDate:(NSDate *)arg1 ;
-(id)init;
-(void)engagementEvent;
-(void)setEngaged:(BOOL)arg1 ;
-(int)locationType;
-(BOOL)engaged;
-(int)engagements;
-(void)setEngagements:(int)arg1 ;
-(int)parkingEvents;
-(int)assistances;
-(int)assistedParkingEvents;
-(int)engagedParkingEvents;
-(id)initWithLocationType:(int)arg1 ;
-(void)clearScoreBoard;
-(void)setAssisted:(BOOL)arg1 ;
-(void)setParkingEvents:(int)arg1 ;
-(void)setEngagedParkingEvents:(int)arg1 ;
-(void)setAssistedParkingEvents:(int)arg1 ;
-(void)setAssistances:(int)arg1 ;
-(void)setSuppressedEvents:(int)arg1 ;
-(int)suppressedEvents;
-(BOOL)assisted;
-(void)copyToMetric:(id)arg1 ;
-(void)parkingEvent;
-(void)assistanceEvent;
-(void)suppressedEvent;
@end

