/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:33 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTMapItem;

@interface RTFusedInferredMapItem : NSObject {

	RTMapItem* _mapItem;
	double _confidence;
	unsigned long long _source;

}

@property (nonatomic,retain) RTMapItem * mapItem;                    //@synthesize mapItem=_mapItem - In the implementation block
@property (assign,nonatomic) double confidence;                      //@synthesize confidence=_confidence - In the implementation block
@property (assign,nonatomic) unsigned long long source;              //@synthesize source=_source - In the implementation block
+(id)sortFusedInferredMapItems:(id)arg1 confidenceEqualityEpsilon:(double)arg2 referenceLocation:(id)arg3 distanceCalculator:(id)arg4 ascending:(BOOL)arg5 ;
-(double)confidence;
-(id)init;
-(void)setMapItem:(RTMapItem *)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(BOOL)isEqual:(id)arg1 ;
-(id)initWithMapItem:(id)arg1 confidence:(double)arg2 source:(unsigned long long)arg3 ;
-(unsigned long long)source;
-(RTMapItem *)mapItem;
-(void)setConfidence:(double)arg1 ;
-(void)setSource:(unsigned long long)arg1 ;
-(id)convertToInferredMapItem;
-(id)initWithInferredMapItem:(id)arg1 ;
@end

