/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:33 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class NSNumber;

@interface RTHintManagerNotificationDidUpdate : RTNotification {

	NSNumber* _hintSourcesUpdated;

}

@property (nonatomic,retain) NSNumber * hintSourcesUpdated;              //@synthesize hintSourcesUpdated=_hintSourcesUpdated - In the implementation block
+(id)sourcesUpdatedForHints:(id)arg1 ;
-(id)description;
-(NSNumber *)hintSourcesUpdated;
-(id)initWithHints:(id)arg1 ;
-(void)setHintSourcesUpdated:(NSNumber *)arg1 ;
@end

