/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:33 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface RTLearnedLocationReconcilerModelContext : NSObject {

	NSArray* _devices;
	NSArray* _overlappingVisits;

}

@property (nonatomic,retain) NSArray * devices;                        //@synthesize devices=_devices - In the implementation block
@property (nonatomic,retain) NSArray * overlappingVisits;              //@synthesize overlappingVisits=_overlappingVisits - In the implementation block
-(NSArray *)devices;
-(void)setDevices:(NSArray *)arg1 ;
-(void)setOverlappingVisits:(NSArray *)arg1 ;
-(NSArray *)overlappingVisits;
@end

