/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:34 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSObject, RTPersistenceManager;

@interface RTLearnedLocationReconcilerPerDevice : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	RTPersistenceManager* _persistenceManager;

}

@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                     //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) RTPersistenceManager * persistenceManager;              //@synthesize persistenceManager=_persistenceManager - In the implementation block
-(void)setPersistenceManager:(RTPersistenceManager *)arg1 ;
-(RTPersistenceManager *)persistenceManager;
-(id)init;
-(id)initWithPersistenceManager:(id)arg1 ;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)performReconciliationWithHandler:(/*^block*/id)arg1 ;
-(void)collapseReconciledVisitsToLocationsOfInterest:(id)arg1 context:(id)arg2 handler:(/*^block*/id)arg3 ;
-(id)_sortDescriptorForReconciliation;
@end

