/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:32 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RTLearnedLocationEngineProtocol <NSObject>
@optional
-(void)learnedLocationEngineWillBeginTraining:(id)arg1;
-(void)learnedLocationEngineDidFinishTraining:(id)arg1;

@required
-(void)learnedLocationEngineDidUpdate:(id)arg1 intervalSinceLastUpdate:(double)arg2;

@end

