/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:33 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSPersistentStoreCoordinator, NSManagedObjectID, RTDarwinNotificationHelper;

@interface RTPersistenceRemoteStore : NSObject {

	NSPersistentStoreCoordinator* _coordinator;
	NSManagedObjectID* _currentDeviceManagedObjectId;
	RTDarwinNotificationHelper* _notificationHelper;

}
-(id)init;
-(id)createManagedObjectContext;
-(id)initWithReadOnly:(BOOL)arg1 ;
-(id)_createManagedObjectContext;
-(void)updateCurrentDeviceMOIDWithContext:(id)arg1 ;
@end

