/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:32 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate;

@interface RTReviewedPlace : NSObject {

	BOOL _hasUserReviewed;
	unsigned long long _muid;
	NSDate* _lastSuggestedReviewDate;
	NSDate* _modifiedDate;

}

@property (nonatomic,readonly) unsigned long long muid;                       //@synthesize muid=_muid - In the implementation block
@property (nonatomic,readonly) NSDate * lastSuggestedReviewDate;              //@synthesize lastSuggestedReviewDate=_lastSuggestedReviewDate - In the implementation block
@property (nonatomic,readonly) BOOL hasUserReviewed;                          //@synthesize hasUserReviewed=_hasUserReviewed - In the implementation block
@property (nonatomic,readonly) NSDate * modifiedDate;                         //@synthesize modifiedDate=_modifiedDate - In the implementation block
-(unsigned long long)muid;
-(id)init;
-(NSDate *)modifiedDate;
-(id)description;
-(NSDate *)lastSuggestedReviewDate;
-(BOOL)hasUserReviewed;
-(id)initWithMuid:(unsigned long long)arg1 lastSuggestedReviewDate:(id)arg2 hasUserReviewed:(BOOL)arg3 modifiedDate:(id)arg4 ;
@end

