/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:33 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDateInterval, NSNumber;

@interface RTStoredSettledStateTransitionEnumerationOptions : NSObject {

	BOOL _ascending;
	NSDateInterval* _dateInterval;
	NSNumber* _limit;
	unsigned long long _batchSize;

}

@property (nonatomic,readonly) BOOL ascending;                            //@synthesize ascending=_ascending - In the implementation block
@property (nonatomic,copy) NSDateInterval * dateInterval;                 //@synthesize dateInterval=_dateInterval - In the implementation block
@property (nonatomic,readonly) NSNumber * limit;                          //@synthesize limit=_limit - In the implementation block
@property (nonatomic,readonly) unsigned long long batchSize;              //@synthesize batchSize=_batchSize - In the implementation block
-(void)setDateInterval:(NSDateInterval *)arg1 ;
-(BOOL)ascending;
-(NSDateInterval *)dateInterval;
-(NSNumber *)limit;
-(id)description;
-(unsigned long long)batchSize;
-(id)initWithAscending:(BOOL)arg1 dateInterval:(id)arg2 limit:(id)arg3 batchSize:(unsigned long long)arg4 ;
@end

