/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:33 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@interface RTUserSessionMonitorNotificationConsoleUserDidChange : RTNotification {

	BOOL _activeUser;

}

@property (getter=activeUser,nonatomic,readonly) BOOL activeUser;              //@synthesize activeUser=_activeUser - In the implementation block
-(id)init;
-(BOOL)activeUser;
-(id)initWithactiveUser:(BOOL)arg1 ;
@end

