/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:59:33 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class RTVisitLocationPoints, RTVisit;

@interface RTVisitCluster : NSObject {

	RTVisitLocationPoints* _points;
	RTVisit* _visit;

}

@property (nonatomic,readonly) RTVisitLocationPoints * points;              //@synthesize points=_points - In the implementation block
@property (nonatomic,readonly) RTVisit * visit;                             //@synthesize visit=_visit - In the implementation block
-(BOOL)isDateInside:(id)arg1 ;
-(id)init;
-(BOOL)isCompleteAndExitDateIsEqualToDate:(id)arg1 ;
-(BOOL)isExitDateBeforeDate:(id)arg1 ;
-(id)initWithPoints:(id)arg1 visit:(id)arg2 ;
-(RTVisitLocationPoints *)points;
-(id)description;
-(BOOL)isPartialAndExitDateIsEqualToDate:(id)arg1 ;
-(RTVisit *)visit;
-(id)initWithPoints:(id)arg1 ;
@end

