/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:44 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface FPImageEnumerator : NSObject {

	NSArray* _images;
	unsigned long long _index;

}
-(id)initWithImages:(id)arg1 ;
-(id)nextImageForStart:(unsigned long long)arg1 end:(unsigned long long)arg2 ;
@end

