/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:44 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableSet;

@interface FPProcessGroupMinimal : NSObject {

	NSMutableSet* _processes;
	unsigned long long _hashValue;

}

@property (nonatomic,retain) NSMutableSet * processes;                  //@synthesize processes=_processes - In the implementation block
@property (assign,nonatomic) unsigned long long hashValue;              //@synthesize hashValue=_hashValue - In the implementation block
-(id)immutableCopy;
-(id)init;
-(NSMutableSet *)processes;
-(unsigned long long)hash;
-(id)description;
-(void)addProcess:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hashValue;
-(void)setHashValue:(unsigned long long)arg1 ;
-(void)setProcesses:(NSMutableSet *)arg1 ;
@end

