/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:54:48 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/swift/libswiftUIKit.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/_UIContentConfigurationInternal.h>

@class NSString;

@interface _TtC5UIKitP33_B626C8241CE05CD32813912C34F02B2229_UICustomContentConfiguration : NSObject <_UIContentConfigurationInternal> {

	 wrappedConfiguration;
	 $__lazy_storage_$_wrappedConfigurationIdentifier;

}

@property (readonly,nonatomic) NSString * description; 
-(id)init;
-(id)copyWithZone:(void*)arg1 ;
-(NSString *)description;
-(id)updatedConfigurationForState:(id)arg1 ;
-(id)makeContentView;
-(id)_wrappedConfigurationIdentifier;
@end

