/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:35 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDAddressBookSyncFullSyncEvent : PBCodable <NSCopying> {

	unsigned long long _approximateRecordCount;
	unsigned long long _recordsPerSecond;
	unsigned long long _timestamp;
	int _result;
	SCD_Struct_AW1 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                           //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasResult; 
@property (assign,nonatomic) int result;                                             //@synthesize result=_result - In the implementation block
@property (assign,nonatomic) BOOL hasRecordsPerSecond; 
@property (assign,nonatomic) unsigned long long recordsPerSecond;                    //@synthesize recordsPerSecond=_recordsPerSecond - In the implementation block
@property (assign,nonatomic) BOOL hasApproximateRecordCount; 
@property (assign,nonatomic) unsigned long long approximateRecordCount;              //@synthesize approximateRecordCount=_approximateRecordCount - In the implementation block
-(void)setResult:(int)arg1 ;
-(BOOL)hasResult;
-(int)result;
-(unsigned long long)timestamp;
-(void)setHasResult:(BOOL)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)hash;
-(id)resultAsString:(int)arg1 ;
-(int)StringAsResult:(id)arg1 ;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)hasTimestamp;
-(void)writeTo:(id)arg1 ;
-(void)setRecordsPerSecond:(unsigned long long)arg1 ;
-(void)setHasRecordsPerSecond:(BOOL)arg1 ;
-(BOOL)hasRecordsPerSecond;
-(void)setApproximateRecordCount:(unsigned long long)arg1 ;
-(void)setHasApproximateRecordCount:(BOOL)arg1 ;
-(BOOL)hasApproximateRecordCount;
-(unsigned long long)recordsPerSecond;
-(unsigned long long)approximateRecordCount;
@end

