/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:35 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDCoreRoutineRankRoutesRequestedInstance : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	int _highestRankedRouteScore;
	int _numberOfInputRoutes;
	SCD_Struct_AW4 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                 //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasNumberOfInputRoutes; 
@property (assign,nonatomic) int numberOfInputRoutes;                      //@synthesize numberOfInputRoutes=_numberOfInputRoutes - In the implementation block
@property (assign,nonatomic) BOOL hasHighestRankedRouteScore; 
@property (assign,nonatomic) int highestRankedRouteScore;                  //@synthesize highestRankedRouteScore=_highestRankedRouteScore - In the implementation block
-(unsigned long long)timestamp;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)hasTimestamp;
-(void)writeTo:(id)arg1 ;
-(void)setNumberOfInputRoutes:(int)arg1 ;
-(void)setHasNumberOfInputRoutes:(BOOL)arg1 ;
-(BOOL)hasNumberOfInputRoutes;
-(void)setHighestRankedRouteScore:(int)arg1 ;
-(void)setHasHighestRankedRouteScore:(BOOL)arg1 ;
-(BOOL)hasHighestRankedRouteScore;
-(int)numberOfInputRoutes;
-(int)highestRankedRouteScore;
@end

