/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:35 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDCoreRoutinePersistenceMirroringOperations : PBCodable <NSCopying> {

	long long _timeIntervalSinceLastOperation;
	unsigned long long _timestamp;
	int _deviceClass;
	int _errorCount;
	int _operationType;
	int _qualityOfService;
	int _recordsChanged;
	SCD_Struct_AW16 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                          //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasDeviceClass; 
@property (assign,nonatomic) int deviceClass;                                       //@synthesize deviceClass=_deviceClass - In the implementation block
@property (assign,nonatomic) BOOL hasOperationType; 
@property (assign,nonatomic) int operationType;                                     //@synthesize operationType=_operationType - In the implementation block
@property (assign,nonatomic) BOOL hasRecordsChanged; 
@property (assign,nonatomic) int recordsChanged;                                    //@synthesize recordsChanged=_recordsChanged - In the implementation block
@property (assign,nonatomic) BOOL hasErrorCount; 
@property (assign,nonatomic) int errorCount;                                        //@synthesize errorCount=_errorCount - In the implementation block
@property (assign,nonatomic) BOOL hasTimeIntervalSinceLastOperation; 
@property (assign,nonatomic) long long timeIntervalSinceLastOperation;              //@synthesize timeIntervalSinceLastOperation=_timeIntervalSinceLastOperation - In the implementation block
@property (assign,nonatomic) BOOL hasQualityOfService; 
@property (assign,nonatomic) int qualityOfService;                                  //@synthesize qualityOfService=_qualityOfService - In the implementation block
-(BOOL)hasDeviceClass;
-(unsigned long long)timestamp;
-(void)setDeviceClass:(int)arg1 ;
-(int)deviceClass;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setOperationType:(int)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(void)setHasDeviceClass:(BOOL)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(void)setErrorCount:(int)arg1 ;
-(BOOL)hasTimestamp;
-(BOOL)hasQualityOfService;
-(void)setQualityOfService:(int)arg1 ;
-(int)errorCount;
-(int)qualityOfService;
-(int)operationType;
-(void)setHasQualityOfService:(BOOL)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)setHasOperationType:(BOOL)arg1 ;
-(BOOL)hasOperationType;
-(void)setRecordsChanged:(int)arg1 ;
-(void)setHasRecordsChanged:(BOOL)arg1 ;
-(BOOL)hasRecordsChanged;
-(void)setHasErrorCount:(BOOL)arg1 ;
-(BOOL)hasErrorCount;
-(void)setTimeIntervalSinceLastOperation:(long long)arg1 ;
-(void)setHasTimeIntervalSinceLastOperation:(BOOL)arg1 ;
-(BOOL)hasTimeIntervalSinceLastOperation;
-(int)recordsChanged;
-(long long)timeIntervalSinceLastOperation;
@end

