/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:35 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/RTMetricManagerMetricIdProtocol.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableArray, NSString;

@interface AWDCoreRoutineLMPScoreBoard : PBCodable <RTMetricManagerMetricIdProtocol, NSCopying> {

	unsigned long long _timestamp;
	NSMutableArray* _instances;
	NSMutableArray* _secondaryInstances;
	SCD_Struct_AW5 _has;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                     //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,retain) NSMutableArray * instances;                       //@synthesize instances=_instances - In the implementation block
@property (nonatomic,retain) NSMutableArray * secondaryInstances;              //@synthesize secondaryInstances=_secondaryInstances - In the implementation block
+(Class)instancesType;
+(Class)secondaryInstancesType;
-(long long)metricId;
-(BOOL)valid:(id*)arg1 ;
-(NSString *)description;
-(id)_init;
-(unsigned long long)timestamp;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)dealloc;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)hasTimestamp;
-(NSMutableArray *)instances;
-(void)writeTo:(id)arg1 ;
-(unsigned long long)instancesCount;
-(void)addInstances:(id)arg1 ;
-(void)clearInstances;
-(void)setInstances:(NSMutableArray *)arg1 ;
-(void)setSecondaryInstances:(NSMutableArray *)arg1 ;
-(void)addSecondaryInstances:(id)arg1 ;
-(id)instancesAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)secondaryInstancesCount;
-(void)clearSecondaryInstances;
-(id)secondaryInstancesAtIndex:(unsigned long long)arg1 ;
-(NSMutableArray *)secondaryInstances;
@end

