/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:35 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class AWDCoreRoutineLocationAwarenessBasicHistogram;

@interface AWDCoreRoutineLocationAwarenessHeartbeatStatistics : PBCodable <NSCopying> {

	unsigned long long _duration;
	unsigned long long _timestamp;
	AWDCoreRoutineLocationAwarenessBasicHistogram* _heartbeatActiveRequestCount;
	AWDCoreRoutineLocationAwarenessBasicHistogram* _heartbeatTimerFiringCount;
	AWDCoreRoutineLocationAwarenessBasicHistogram* _heartbeatValidLocationCount;
	SCD_Struct_AW3 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                                                             //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasDuration; 
@property (assign,nonatomic) unsigned long long duration;                                                              //@synthesize duration=_duration - In the implementation block
@property (nonatomic,readonly) BOOL hasHeartbeatTimerFiringCount; 
@property (nonatomic,retain) AWDCoreRoutineLocationAwarenessBasicHistogram * heartbeatTimerFiringCount;                //@synthesize heartbeatTimerFiringCount=_heartbeatTimerFiringCount - In the implementation block
@property (nonatomic,readonly) BOOL hasHeartbeatActiveRequestCount; 
@property (nonatomic,retain) AWDCoreRoutineLocationAwarenessBasicHistogram * heartbeatActiveRequestCount;              //@synthesize heartbeatActiveRequestCount=_heartbeatActiveRequestCount - In the implementation block
@property (nonatomic,readonly) BOOL hasHeartbeatValidLocationCount; 
@property (nonatomic,retain) AWDCoreRoutineLocationAwarenessBasicHistogram * heartbeatValidLocationCount;              //@synthesize heartbeatValidLocationCount=_heartbeatValidLocationCount - In the implementation block
-(BOOL)hasDuration;
-(void)setHasDuration:(BOOL)arg1 ;
-(unsigned long long)timestamp;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setDuration:(unsigned long long)arg1 ;
-(void)dealloc;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)hasTimestamp;
-(unsigned long long)duration;
-(void)writeTo:(id)arg1 ;
-(void)setHeartbeatTimerFiringCount:(AWDCoreRoutineLocationAwarenessBasicHistogram *)arg1 ;
-(void)setHeartbeatActiveRequestCount:(AWDCoreRoutineLocationAwarenessBasicHistogram *)arg1 ;
-(void)setHeartbeatValidLocationCount:(AWDCoreRoutineLocationAwarenessBasicHistogram *)arg1 ;
-(BOOL)hasHeartbeatTimerFiringCount;
-(BOOL)hasHeartbeatActiveRequestCount;
-(BOOL)hasHeartbeatValidLocationCount;
-(AWDCoreRoutineLocationAwarenessBasicHistogram *)heartbeatTimerFiringCount;
-(AWDCoreRoutineLocationAwarenessBasicHistogram *)heartbeatActiveRequestCount;
-(AWDCoreRoutineLocationAwarenessBasicHistogram *)heartbeatValidLocationCount;
@end

