/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:36 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDIDSRegistrationControlChosen : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	int _registrationControlStatus;
	int _registrationType;
	BOOL _isInterestingRegion;
	SCD_Struct_AW1 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                   //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasRegistrationType; 
@property (assign,nonatomic) int registrationType;                           //@synthesize registrationType=_registrationType - In the implementation block
@property (assign,nonatomic) BOOL hasRegistrationControlStatus; 
@property (assign,nonatomic) int registrationControlStatus;                  //@synthesize registrationControlStatus=_registrationControlStatus - In the implementation block
@property (assign,nonatomic) BOOL hasIsInterestingRegion; 
@property (assign,nonatomic) BOOL isInterestingRegion;                       //@synthesize isInterestingRegion=_isInterestingRegion - In the implementation block
-(unsigned long long)timestamp;
-(void)setRegistrationType:(int)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(int)registrationControlStatus;
-(void)setRegistrationControlStatus:(int)arg1 ;
-(BOOL)isInterestingRegion;
-(void)setIsInterestingRegion:(BOOL)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(int)registrationType;
-(BOOL)hasTimestamp;
-(void)writeTo:(id)arg1 ;
-(void)setHasRegistrationType:(BOOL)arg1 ;
-(BOOL)hasRegistrationType;
-(void)setHasRegistrationControlStatus:(BOOL)arg1 ;
-(BOOL)hasRegistrationControlStatus;
-(void)setHasIsInterestingRegion:(BOOL)arg1 ;
-(BOOL)hasIsInterestingRegion;
@end

