/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:36 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDIDSLocalDeliverySocketOpened : PBCodable <NSCopying> {

	unsigned long long _isToDefaultPairedDevice;
	unsigned long long _openError;
	unsigned long long _priority;
	unsigned long long _socketError;
	unsigned long long _timestamp;
	NSString* _guid;
	NSString* _service;
	NSString* _streamName;
	SCD_Struct_AW2 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                            //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL hasService; 
@property (nonatomic,retain) NSString * service;                                      //@synthesize service=_service - In the implementation block
@property (assign,nonatomic) BOOL hasIsToDefaultPairedDevice; 
@property (assign,nonatomic) unsigned long long isToDefaultPairedDevice;              //@synthesize isToDefaultPairedDevice=_isToDefaultPairedDevice - In the implementation block
@property (assign,nonatomic) BOOL hasOpenError; 
@property (assign,nonatomic) unsigned long long openError;                            //@synthesize openError=_openError - In the implementation block
@property (assign,nonatomic) BOOL hasSocketError; 
@property (assign,nonatomic) unsigned long long socketError;                          //@synthesize socketError=_socketError - In the implementation block
@property (assign,nonatomic) BOOL hasPriority; 
@property (assign,nonatomic) unsigned long long priority;                             //@synthesize priority=_priority - In the implementation block
@property (nonatomic,readonly) BOOL hasStreamName; 
@property (nonatomic,retain) NSString * streamName;                                   //@synthesize streamName=_streamName - In the implementation block
@property (nonatomic,readonly) BOOL hasGuid; 
@property (nonatomic,retain) NSString * guid;                                         //@synthesize guid=_guid - In the implementation block
-(void)setPriority:(unsigned long long)arg1 ;
-(void)setGuid:(NSString *)arg1 ;
-(unsigned long long)timestamp;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setIsToDefaultPairedDevice:(unsigned long long)arg1 ;
-(void)setHasPriority:(BOOL)arg1 ;
-(void)dealloc;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasGuid;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(NSString *)service;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)hash;
-(void)setStreamName:(NSString *)arg1 ;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(unsigned long long)openError;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)hasService;
-(unsigned long long)isToDefaultPairedDevice;
-(unsigned long long)socketError;
-(BOOL)hasTimestamp;
-(NSString *)streamName;
-(BOOL)hasPriority;
-(void)setService:(NSString *)arg1 ;
-(NSString *)guid;
-(unsigned long long)priority;
-(void)writeTo:(id)arg1 ;
-(void)setHasIsToDefaultPairedDevice:(BOOL)arg1 ;
-(BOOL)hasIsToDefaultPairedDevice;
-(void)setSocketError:(unsigned long long)arg1 ;
-(void)setHasSocketError:(BOOL)arg1 ;
-(BOOL)hasSocketError;
-(BOOL)hasStreamName;
-(void)setOpenError:(unsigned long long)arg1 ;
-(void)setHasOpenError:(BOOL)arg1 ;
-(BOOL)hasOpenError;
@end

