/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:36 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDIDSSessionCancelSent : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	NSString* _guid;
	unsigned _numberOfRecipients;
	unsigned _remoteSessionEndReason;
	SCD_Struct_AW4 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                 //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL hasGuid; 
@property (nonatomic,retain) NSString * guid;                              //@synthesize guid=_guid - In the implementation block
@property (assign,nonatomic) BOOL hasNumberOfRecipients; 
@property (assign,nonatomic) unsigned numberOfRecipients;                  //@synthesize numberOfRecipients=_numberOfRecipients - In the implementation block
@property (assign,nonatomic) BOOL hasRemoteSessionEndReason; 
@property (assign,nonatomic) unsigned remoteSessionEndReason;              //@synthesize remoteSessionEndReason=_remoteSessionEndReason - In the implementation block
-(void)setGuid:(NSString *)arg1 ;
-(unsigned long long)timestamp;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)dealloc;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasGuid;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)hasTimestamp;
-(unsigned)numberOfRecipients;
-(NSString *)guid;
-(void)writeTo:(id)arg1 ;
-(unsigned)remoteSessionEndReason;
-(void)setNumberOfRecipients:(unsigned)arg1 ;
-(void)setHasNumberOfRecipients:(BOOL)arg1 ;
-(BOOL)hasNumberOfRecipients;
-(void)setRemoteSessionEndReason:(unsigned)arg1 ;
-(void)setHasRemoteSessionEndReason:(BOOL)arg1 ;
-(BOOL)hasRemoteSessionEndReason;
@end

