/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:39 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDSpringBoardClawGesture : PBCodable <NSCopying> {

	unsigned long long _duration;
	unsigned long long _timestamp;
	BOOL _didPressLock;
	BOOL _didPressVolumeDown;
	BOOL _didPressVolumeUp;
	BOOL _didTriggerSOS;
	SCD_Struct_AW10 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;              //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasDidPressLock; 
@property (assign,nonatomic) BOOL didPressLock;                         //@synthesize didPressLock=_didPressLock - In the implementation block
@property (assign,nonatomic) BOOL hasDidPressVolumeUp; 
@property (assign,nonatomic) BOOL didPressVolumeUp;                     //@synthesize didPressVolumeUp=_didPressVolumeUp - In the implementation block
@property (assign,nonatomic) BOOL hasDidPressVolumeDown; 
@property (assign,nonatomic) BOOL didPressVolumeDown;                   //@synthesize didPressVolumeDown=_didPressVolumeDown - In the implementation block
@property (assign,nonatomic) BOOL hasDidTriggerSOS; 
@property (assign,nonatomic) BOOL didTriggerSOS;                        //@synthesize didTriggerSOS=_didTriggerSOS - In the implementation block
@property (assign,nonatomic) BOOL hasDuration; 
@property (assign,nonatomic) unsigned long long duration;               //@synthesize duration=_duration - In the implementation block
-(BOOL)hasDuration;
-(void)setHasDuration:(BOOL)arg1 ;
-(unsigned long long)timestamp;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setDuration:(unsigned long long)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)hasTimestamp;
-(unsigned long long)duration;
-(void)writeTo:(id)arg1 ;
-(void)setDidPressLock:(BOOL)arg1 ;
-(void)setDidPressVolumeUp:(BOOL)arg1 ;
-(void)setDidPressVolumeDown:(BOOL)arg1 ;
-(void)setDidTriggerSOS:(BOOL)arg1 ;
-(BOOL)didTriggerSOS;
-(void)setHasDidPressLock:(BOOL)arg1 ;
-(BOOL)hasDidPressLock;
-(void)setHasDidPressVolumeUp:(BOOL)arg1 ;
-(BOOL)hasDidPressVolumeUp;
-(void)setHasDidPressVolumeDown:(BOOL)arg1 ;
-(BOOL)hasDidPressVolumeDown;
-(void)setHasDidTriggerSOS:(BOOL)arg1 ;
-(BOOL)hasDidTriggerSOS;
-(BOOL)didPressLock;
-(BOOL)didPressVolumeUp;
-(BOOL)didPressVolumeDown;
@end

