/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:39 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDSOSLongPressTriggersEmergencySOS : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	BOOL _longPressTriggersEmergencySOS;
	SCD_Struct_AW3 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                       //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasLongPressTriggersEmergencySOS; 
@property (assign,nonatomic) BOOL longPressTriggersEmergencySOS;                 //@synthesize longPressTriggersEmergencySOS=_longPressTriggersEmergencySOS - In the implementation block
-(unsigned long long)timestamp;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)hash;
-(void)setLongPressTriggersEmergencySOS:(BOOL)arg1 ;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)hasTimestamp;
-(BOOL)longPressTriggersEmergencySOS;
-(void)writeTo:(id)arg1 ;
-(void)setHasLongPressTriggersEmergencySOS:(BOOL)arg1 ;
-(BOOL)hasLongPressTriggersEmergencySOS;
@end

