/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:39 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface AWDSpringBoardAppBrightness : PBCodable <NSCopying> {

	unsigned long long _brightness;
	unsigned long long _duration;
	unsigned long long _timestamp;
	NSString* _appBundleID;
	SCD_Struct_AW4 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;               //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL hasAppBundleID; 
@property (nonatomic,retain) NSString * appBundleID;                     //@synthesize appBundleID=_appBundleID - In the implementation block
@property (assign,nonatomic) BOOL hasBrightness; 
@property (assign,nonatomic) unsigned long long brightness;              //@synthesize brightness=_brightness - In the implementation block
@property (assign,nonatomic) BOOL hasDuration; 
@property (assign,nonatomic) unsigned long long duration;                //@synthesize duration=_duration - In the implementation block
-(BOOL)hasDuration;
-(void)setHasDuration:(BOOL)arg1 ;
-(unsigned long long)timestamp;
-(void)setHasBrightness:(BOOL)arg1 ;
-(BOOL)hasBrightness;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setDuration:(unsigned long long)arg1 ;
-(void)dealloc;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)brightness;
-(unsigned long long)hash;
-(void)setAppBundleID:(NSString *)arg1 ;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)hasTimestamp;
-(unsigned long long)duration;
-(void)writeTo:(id)arg1 ;
-(NSString *)appBundleID;
-(void)setBrightness:(unsigned long long)arg1 ;
-(BOOL)hasAppBundleID;
@end

