/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:41 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData, NSString;

@interface AWDWiFiOtaSystemInfo : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	NSData* _beaconInfo;
	NSString* _bssid;
	unsigned _channel;
	unsigned _channelWidth;
	NSString* _locale;
	NSString* _localeSource;
	NSString* _ssid;
	NSString* _wpsConfigMethods;
	NSString* _wpsDeviceNameData;
	NSString* _wpsDeviceNameElement;
	NSString* _wpsManufacturerElement;
	NSString* _wpsModelName;
	NSString* _wpsModelNumber;
	NSString* _wpsPrimaryDeviceTypeCategory;
	NSString* _wpsPrimaryDeviceTypeSubCategory;
	NSString* _wpsResponseType;
	SCD_Struct_AW4 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                            //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL hasBeaconInfo; 
@property (nonatomic,retain) NSData * beaconInfo;                                     //@synthesize beaconInfo=_beaconInfo - In the implementation block
@property (nonatomic,readonly) BOOL hasSsid; 
@property (nonatomic,retain) NSString * ssid;                                         //@synthesize ssid=_ssid - In the implementation block
@property (nonatomic,readonly) BOOL hasBssid; 
@property (nonatomic,retain) NSString * bssid;                                        //@synthesize bssid=_bssid - In the implementation block
@property (nonatomic,readonly) BOOL hasWpsResponseType; 
@property (nonatomic,retain) NSString * wpsResponseType;                              //@synthesize wpsResponseType=_wpsResponseType - In the implementation block
@property (nonatomic,readonly) BOOL hasWpsManufacturerElement; 
@property (nonatomic,retain) NSString * wpsManufacturerElement;                       //@synthesize wpsManufacturerElement=_wpsManufacturerElement - In the implementation block
@property (nonatomic,readonly) BOOL hasWpsModelName; 
@property (nonatomic,retain) NSString * wpsModelName;                                 //@synthesize wpsModelName=_wpsModelName - In the implementation block
@property (nonatomic,readonly) BOOL hasWpsModelNumber; 
@property (nonatomic,retain) NSString * wpsModelNumber;                               //@synthesize wpsModelNumber=_wpsModelNumber - In the implementation block
@property (nonatomic,readonly) BOOL hasWpsPrimaryDeviceTypeCategory; 
@property (nonatomic,retain) NSString * wpsPrimaryDeviceTypeCategory;                 //@synthesize wpsPrimaryDeviceTypeCategory=_wpsPrimaryDeviceTypeCategory - In the implementation block
@property (nonatomic,readonly) BOOL hasWpsPrimaryDeviceTypeSubCategory; 
@property (nonatomic,retain) NSString * wpsPrimaryDeviceTypeSubCategory;              //@synthesize wpsPrimaryDeviceTypeSubCategory=_wpsPrimaryDeviceTypeSubCategory - In the implementation block
@property (nonatomic,readonly) BOOL hasWpsDeviceNameElement; 
@property (nonatomic,retain) NSString * wpsDeviceNameElement;                         //@synthesize wpsDeviceNameElement=_wpsDeviceNameElement - In the implementation block
@property (nonatomic,readonly) BOOL hasWpsDeviceNameData; 
@property (nonatomic,retain) NSString * wpsDeviceNameData;                            //@synthesize wpsDeviceNameData=_wpsDeviceNameData - In the implementation block
@property (nonatomic,readonly) BOOL hasWpsConfigMethods; 
@property (nonatomic,retain) NSString * wpsConfigMethods;                             //@synthesize wpsConfigMethods=_wpsConfigMethods - In the implementation block
@property (nonatomic,readonly) BOOL hasLocale; 
@property (nonatomic,retain) NSString * locale;                                       //@synthesize locale=_locale - In the implementation block
@property (nonatomic,readonly) BOOL hasLocaleSource; 
@property (nonatomic,retain) NSString * localeSource;                                 //@synthesize localeSource=_localeSource - In the implementation block
@property (assign,nonatomic) BOOL hasChannel; 
@property (assign,nonatomic) unsigned channel;                                        //@synthesize channel=_channel - In the implementation block
@property (assign,nonatomic) BOOL hasChannelWidth; 
@property (assign,nonatomic) unsigned channelWidth;                                   //@synthesize channelWidth=_channelWidth - In the implementation block
-(NSString *)ssid;
-(NSString *)locale;
-(void)setChannel:(unsigned)arg1 ;
-(void)setWpsPrimaryDeviceTypeSubCategory:(NSString *)arg1 ;
-(unsigned long long)timestamp;
-(void)setWpsPrimaryDeviceTypeCategory:(NSString *)arg1 ;
-(void)setWpsManufacturerElement:(NSString *)arg1 ;
-(void)setWpsModelNumber:(NSString *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(BOOL)hasWpsModelName;
-(NSString *)wpsManufacturerElement;
-(void)dealloc;
-(void)setHasChannel:(BOOL)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(void)setHasChannelWidth:(BOOL)arg1 ;
-(unsigned)channel;
-(NSString *)wpsResponseType;
-(BOOL)hasLocale;
-(BOOL)hasWpsPrimaryDeviceTypeSubCategory;
-(BOOL)hasWpsModelNumber;
-(BOOL)readFrom:(id)arg1 ;
-(void)setLocale:(NSString *)arg1 ;
-(void)setSsid:(NSString *)arg1 ;
-(unsigned long long)hash;
-(BOOL)hasWpsDeviceNameData;
-(void)setWpsModelName:(NSString *)arg1 ;
-(id)description;
-(NSString *)wpsDeviceNameData;
-(void)setWpsDeviceNameData:(NSString *)arg1 ;
-(BOOL)hasChannelWidth;
-(NSString *)bssid;
-(void)copyTo:(id)arg1 ;
-(NSString *)wpsConfigMethods;
-(NSString *)wpsModelName;
-(NSString *)wpsPrimaryDeviceTypeSubCategory;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(void)setWpsConfigMethods:(NSString *)arg1 ;
-(BOOL)hasTimestamp;
-(void)setLocaleSource:(NSString *)arg1 ;
-(NSString *)wpsDeviceNameElement;
-(void)setBssid:(NSString *)arg1 ;
-(NSData *)beaconInfo;
-(void)setBeaconInfo:(NSData *)arg1 ;
-(BOOL)hasBeaconInfo;
-(NSString *)localeSource;
-(BOOL)hasWpsManufacturerElement;
-(BOOL)hasWpsDeviceNameElement;
-(BOOL)hasWpsPrimaryDeviceTypeCategory;
-(BOOL)hasWpsResponseType;
-(NSString *)wpsModelNumber;
-(BOOL)hasChannel;
-(BOOL)hasLocaleSource;
-(void)setWpsResponseType:(NSString *)arg1 ;
-(NSString *)wpsPrimaryDeviceTypeCategory;
-(unsigned)channelWidth;
-(void)setWpsDeviceNameElement:(NSString *)arg1 ;
-(BOOL)hasSsid;
-(void)writeTo:(id)arg1 ;
-(BOOL)hasWpsConfigMethods;
-(void)setChannelWidth:(unsigned)arg1 ;
-(BOOL)hasBssid;
@end

