/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:40 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDWiFiLTECoexBin : PBCodable <NSCopying> {

	unsigned long long _ctsnotrxafterrts;
	unsigned long long _rxframe;
	unsigned long long _rxrtry;
	unsigned long long _txassocreq;
	unsigned long long _txassocrsp;
	unsigned long long _txdeauth;
	unsigned long long _txframe;
	unsigned long long _txnocts;
	unsigned long long _txreassocreq;
	unsigned long long _txreassocrsp;
	unsigned long long _txretrans;
	unsigned long long _txrts;
	SCD_Struct_AW8 _has;

}

@property (assign,nonatomic) BOOL hasRxframe; 
@property (assign,nonatomic) unsigned long long rxframe;                       //@synthesize rxframe=_rxframe - In the implementation block
@property (assign,nonatomic) BOOL hasTxframe; 
@property (assign,nonatomic) unsigned long long txframe;                       //@synthesize txframe=_txframe - In the implementation block
@property (assign,nonatomic) BOOL hasRxrtry; 
@property (assign,nonatomic) unsigned long long rxrtry;                        //@synthesize rxrtry=_rxrtry - In the implementation block
@property (assign,nonatomic) BOOL hasTxretrans; 
@property (assign,nonatomic) unsigned long long txretrans;                     //@synthesize txretrans=_txretrans - In the implementation block
@property (assign,nonatomic) BOOL hasTxnocts; 
@property (assign,nonatomic) unsigned long long txnocts;                       //@synthesize txnocts=_txnocts - In the implementation block
@property (assign,nonatomic) BOOL hasTxrts; 
@property (assign,nonatomic) unsigned long long txrts;                         //@synthesize txrts=_txrts - In the implementation block
@property (assign,nonatomic) BOOL hasTxdeauth; 
@property (assign,nonatomic) unsigned long long txdeauth;                      //@synthesize txdeauth=_txdeauth - In the implementation block
@property (assign,nonatomic) BOOL hasTxassocreq; 
@property (assign,nonatomic) unsigned long long txassocreq;                    //@synthesize txassocreq=_txassocreq - In the implementation block
@property (assign,nonatomic) BOOL hasTxassocrsp; 
@property (assign,nonatomic) unsigned long long txassocrsp;                    //@synthesize txassocrsp=_txassocrsp - In the implementation block
@property (assign,nonatomic) BOOL hasTxreassocreq; 
@property (assign,nonatomic) unsigned long long txreassocreq;                  //@synthesize txreassocreq=_txreassocreq - In the implementation block
@property (assign,nonatomic) BOOL hasTxreassocrsp; 
@property (assign,nonatomic) unsigned long long txreassocrsp;                  //@synthesize txreassocrsp=_txreassocrsp - In the implementation block
@property (assign,nonatomic) BOOL hasCtsnotrxafterrts; 
@property (assign,nonatomic) unsigned long long ctsnotrxafterrts;              //@synthesize ctsnotrxafterrts=_ctsnotrxafterrts - In the implementation block
-(void)setTxretrans:(unsigned long long)arg1 ;
-(unsigned long long)txassocreq;
-(BOOL)hasTxreassocreq;
-(BOOL)hasRxrtry;
-(unsigned long long)txretrans;
-(void)setHasCtsnotrxafterrts:(BOOL)arg1 ;
-(BOOL)hasTxrts;
-(void)setTxassocreq:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setTxreassocrsp:(unsigned long long)arg1 ;
-(void)setTxreassocreq:(unsigned long long)arg1 ;
-(BOOL)hasCtsnotrxafterrts;
-(void)setTxrts:(unsigned long long)arg1 ;
-(void)setHasTxrts:(BOOL)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setTxnocts:(unsigned long long)arg1 ;
-(void)setTxframe:(unsigned long long)arg1 ;
-(void)setCtsnotrxafterrts:(unsigned long long)arg1 ;
-(void)setHasTxassocrsp:(BOOL)arg1 ;
-(void)setHasTxreassocreq:(BOOL)arg1 ;
-(void)setHasTxretrans:(BOOL)arg1 ;
-(unsigned long long)hash;
-(void)setTxassocrsp:(unsigned long long)arg1 ;
-(BOOL)hasTxassocreq;
-(void)setHasTxreassocrsp:(BOOL)arg1 ;
-(id)description;
-(void)setHasRxrtry:(BOOL)arg1 ;
-(void)copyTo:(id)arg1 ;
-(unsigned long long)ctsnotrxafterrts;
-(unsigned long long)txreassocrsp;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(void)setTxdeauth:(unsigned long long)arg1 ;
-(unsigned long long)txreassocreq;
-(unsigned long long)txrts;
-(unsigned long long)txframe;
-(void)setRxframe:(unsigned long long)arg1 ;
-(void)setHasTxnocts:(BOOL)arg1 ;
-(void)setHasTxdeauth:(BOOL)arg1 ;
-(BOOL)hasTxdeauth;
-(void)setHasTxassocreq:(BOOL)arg1 ;
-(BOOL)hasTxreassocrsp;
-(void)setHasRxframe:(BOOL)arg1 ;
-(unsigned long long)txdeauth;
-(BOOL)hasTxassocrsp;
-(BOOL)hasTxframe;
-(unsigned long long)rxframe;
-(BOOL)hasRxframe;
-(void)setHasTxframe:(BOOL)arg1 ;
-(void)writeTo:(id)arg1 ;
-(BOOL)hasTxretrans;
-(void)setRxrtry:(unsigned long long)arg1 ;
-(unsigned long long)rxrtry;
-(unsigned long long)txassocrsp;
-(unsigned long long)txnocts;
-(BOOL)hasTxnocts;
@end

