/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:41 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSMutableArray;

@interface AWDWiFiUIJoinEvent : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _error;
	NSString* _process;
	NSString* _section;
	NSMutableArray* _sectionCounts;
	unsigned _securityType;
	SCD_Struct_AW4 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL hasProcess; 
@property (nonatomic,retain) NSString * process;                          //@synthesize process=_process - In the implementation block
@property (assign,nonatomic) BOOL hasSecurityType; 
@property (assign,nonatomic) unsigned securityType;                       //@synthesize securityType=_securityType - In the implementation block
@property (assign,nonatomic) BOOL hasError; 
@property (assign,nonatomic) unsigned error;                              //@synthesize error=_error - In the implementation block
@property (nonatomic,readonly) BOOL hasSection; 
@property (nonatomic,retain) NSString * section;                          //@synthesize section=_section - In the implementation block
@property (nonatomic,retain) NSMutableArray * sectionCounts;              //@synthesize sectionCounts=_sectionCounts - In the implementation block
+(Class)sectionCountsType;
-(BOOL)hasSecurityType;
-(void)setHasSecurityType:(BOOL)arg1 ;
-(NSString *)section;
-(unsigned)securityType;
-(void)setSecurityType:(unsigned)arg1 ;
-(void)setSection:(NSString *)arg1 ;
-(unsigned long long)timestamp;
-(unsigned)error;
-(void)setProcess:(NSString *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)hasError;
-(void)mergeFrom:(id)arg1 ;
-(void)dealloc;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)process;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)hasProcess;
-(BOOL)hasTimestamp;
-(void)setError:(unsigned)arg1 ;
-(void)setHasError:(BOOL)arg1 ;
-(BOOL)hasSection;
-(void)writeTo:(id)arg1 ;
-(NSMutableArray *)sectionCounts;
-(void)setSectionCounts:(NSMutableArray *)arg1 ;
-(void)addSectionCounts:(id)arg1 ;
-(unsigned long long)sectionCountsCount;
-(void)clearSectionCounts;
-(id)sectionCountsAtIndex:(unsigned long long)arg1 ;
@end

