/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:41 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData;

@interface AWDWiFiMetricsManagerLastSSIDInfo : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	NSData* _lastSSIDAttempted;
	NSData* _lastSSIDConnectedTo;
	SCD_Struct_AW5 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;               //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL hasLastSSIDAttempted; 
@property (nonatomic,retain) NSData * lastSSIDAttempted;                 //@synthesize lastSSIDAttempted=_lastSSIDAttempted - In the implementation block
@property (nonatomic,readonly) BOOL hasLastSSIDConnectedTo; 
@property (nonatomic,retain) NSData * lastSSIDConnectedTo;               //@synthesize lastSSIDConnectedTo=_lastSSIDConnectedTo - In the implementation block
-(unsigned long long)timestamp;
-(BOOL)hasLastSSIDConnectedTo;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setLastSSIDAttempted:(NSData *)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)dealloc;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(NSData *)lastSSIDConnectedTo;
-(unsigned long long)hash;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)hasTimestamp;
-(BOOL)hasLastSSIDAttempted;
-(void)setLastSSIDConnectedTo:(NSData *)arg1 ;
-(NSData *)lastSSIDAttempted;
-(void)writeTo:(id)arg1 ;
@end

