/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:41 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDWifiAwdlD2dMigrationStats : PBCodable <NSCopying> {

	unsigned long long _rxBytes;
	unsigned long long _sessionDuration;
	unsigned long long _txBytes;
	unsigned _avgCCA;
	unsigned _channel;
	unsigned _migrationRole;
	int _peerRssi;
	unsigned _txFailureCount;
	SCD_Struct_AW12 _has;

}

@property (assign,nonatomic) BOOL hasSessionDuration; 
@property (assign,nonatomic) unsigned long long sessionDuration;              //@synthesize sessionDuration=_sessionDuration - In the implementation block
@property (assign,nonatomic) BOOL hasChannel; 
@property (assign,nonatomic) unsigned channel;                                //@synthesize channel=_channel - In the implementation block
@property (assign,nonatomic) BOOL hasRxBytes; 
@property (assign,nonatomic) unsigned long long rxBytes;                      //@synthesize rxBytes=_rxBytes - In the implementation block
@property (assign,nonatomic) BOOL hasPeerRssi; 
@property (assign,nonatomic) int peerRssi;                                    //@synthesize peerRssi=_peerRssi - In the implementation block
@property (assign,nonatomic) BOOL hasTxFailureCount; 
@property (assign,nonatomic) unsigned txFailureCount;                         //@synthesize txFailureCount=_txFailureCount - In the implementation block
@property (assign,nonatomic) BOOL hasTxBytes; 
@property (assign,nonatomic) unsigned long long txBytes;                      //@synthesize txBytes=_txBytes - In the implementation block
@property (assign,nonatomic) BOOL hasMigrationRole; 
@property (assign,nonatomic) unsigned migrationRole;                          //@synthesize migrationRole=_migrationRole - In the implementation block
@property (assign,nonatomic) BOOL hasAvgCCA; 
@property (assign,nonatomic) unsigned avgCCA;                                 //@synthesize avgCCA=_avgCCA - In the implementation block
-(void)setChannel:(unsigned)arg1 ;
-(unsigned)txFailureCount;
-(void)setPeerRssi:(int)arg1 ;
-(void)setHasPeerRssi:(BOOL)arg1 ;
-(unsigned long long)txBytes;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)hasSessionDuration;
-(BOOL)hasRxBytes;
-(void)mergeFrom:(id)arg1 ;
-(unsigned)migrationRole;
-(unsigned long long)rxBytes;
-(unsigned)avgCCA;
-(void)setHasChannel:(BOOL)arg1 ;
-(unsigned)channel;
-(int)peerRssi;
-(void)setRxBytes:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setTxBytes:(unsigned long long)arg1 ;
-(unsigned long long)hash;
-(void)setHasTxBytes:(BOOL)arg1 ;
-(void)setSessionDuration:(unsigned long long)arg1 ;
-(id)description;
-(void)setHasSessionDuration:(BOOL)arg1 ;
-(void)setAvgCCA:(unsigned)arg1 ;
-(BOOL)hasPeerRssi;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(void)setHasMigrationRole:(BOOL)arg1 ;
-(unsigned long long)sessionDuration;
-(void)setTxFailureCount:(unsigned)arg1 ;
-(void)setHasTxFailureCount:(BOOL)arg1 ;
-(BOOL)hasTxBytes;
-(void)setHasAvgCCA:(BOOL)arg1 ;
-(BOOL)hasMigrationRole;
-(BOOL)hasTxFailureCount;
-(BOOL)hasAvgCCA;
-(void)setHasRxBytes:(BOOL)arg1 ;
-(void)setMigrationRole:(unsigned)arg1 ;
-(BOOL)hasChannel;
-(void)writeTo:(id)arg1 ;
@end

