/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:41 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableArray;

@interface AWDWiFiSDB : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	unsigned _realTimeSessionStateResultingInSubmission;
	NSMutableArray* _sliceStats;
	SCD_Struct_AW3 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                                    //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,retain) NSMutableArray * sliceStats;                                     //@synthesize sliceStats=_sliceStats - In the implementation block
@property (assign,nonatomic) BOOL hasRealTimeSessionStateResultingInSubmission; 
@property (assign,nonatomic) unsigned realTimeSessionStateResultingInSubmission;              //@synthesize realTimeSessionStateResultingInSubmission=_realTimeSessionStateResultingInSubmission - In the implementation block
+(Class)sliceStatsType;
-(unsigned long long)timestamp;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setHasRealTimeSessionStateResultingInSubmission:(BOOL)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(unsigned long long)sliceStatsCount;
-(void)dealloc;
-(unsigned)realTimeSessionStateResultingInSubmission;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(BOOL)hasRealTimeSessionStateResultingInSubmission;
-(unsigned long long)hash;
-(void)setSliceStats:(NSMutableArray *)arg1 ;
-(void)clearSliceStats;
-(id)description;
-(void)copyTo:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(NSMutableArray *)sliceStats;
-(BOOL)hasTimestamp;
-(id)sliceStatsAtIndex:(unsigned long long)arg1 ;
-(void)setRealTimeSessionStateResultingInSubmission:(unsigned)arg1 ;
-(void)addSliceStats:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
@end

