/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:40 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableArray;

@interface AWDWiFiLTEWCI2Counters : PBCodable <NSCopying> {

	unsigned long long _lteTxPowerLimitCount;
	unsigned long long _lteTxPowerLimitTimeInMS;
	unsigned long long _timeSharingWLANIntervalCount;
	unsigned long long _timeSharingWLANTimeInMS;
	unsigned long long _timestamp;
	unsigned long long _type4DueToTimerExpiryCount;
	unsigned long long _type4HonouredCount;
	unsigned long long _type4HonouredTimeInMS;
	unsigned long long _wlanProtectionFramesDueToLTECoexCount;
	unsigned long long _wlanRxPriCount;
	unsigned long long _wlanRxPriTimeInMS;
	NSMutableArray* _wci2Counters;
	SCD_Struct_AW13 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                                          //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasWlanRxPriTimeInMS; 
@property (assign,nonatomic) unsigned long long wlanRxPriTimeInMS;                                  //@synthesize wlanRxPriTimeInMS=_wlanRxPriTimeInMS - In the implementation block
@property (assign,nonatomic) BOOL hasWlanRxPriCount; 
@property (assign,nonatomic) unsigned long long wlanRxPriCount;                                     //@synthesize wlanRxPriCount=_wlanRxPriCount - In the implementation block
@property (assign,nonatomic) BOOL hasLteTxPowerLimitTimeInMS; 
@property (assign,nonatomic) unsigned long long lteTxPowerLimitTimeInMS;                            //@synthesize lteTxPowerLimitTimeInMS=_lteTxPowerLimitTimeInMS - In the implementation block
@property (assign,nonatomic) BOOL hasLteTxPowerLimitCount; 
@property (assign,nonatomic) unsigned long long lteTxPowerLimitCount;                               //@synthesize lteTxPowerLimitCount=_lteTxPowerLimitCount - In the implementation block
@property (assign,nonatomic) BOOL hasType4HonouredTimeInMS; 
@property (assign,nonatomic) unsigned long long type4HonouredTimeInMS;                              //@synthesize type4HonouredTimeInMS=_type4HonouredTimeInMS - In the implementation block
@property (assign,nonatomic) BOOL hasType4HonouredCount; 
@property (assign,nonatomic) unsigned long long type4HonouredCount;                                 //@synthesize type4HonouredCount=_type4HonouredCount - In the implementation block
@property (assign,nonatomic) BOOL hasTimeSharingWLANTimeInMS; 
@property (assign,nonatomic) unsigned long long timeSharingWLANTimeInMS;                            //@synthesize timeSharingWLANTimeInMS=_timeSharingWLANTimeInMS - In the implementation block
@property (assign,nonatomic) BOOL hasTimeSharingWLANIntervalCount; 
@property (assign,nonatomic) unsigned long long timeSharingWLANIntervalCount;                       //@synthesize timeSharingWLANIntervalCount=_timeSharingWLANIntervalCount - In the implementation block
@property (assign,nonatomic) BOOL hasWlanProtectionFramesDueToLTECoexCount; 
@property (assign,nonatomic) unsigned long long wlanProtectionFramesDueToLTECoexCount;              //@synthesize wlanProtectionFramesDueToLTECoexCount=_wlanProtectionFramesDueToLTECoexCount - In the implementation block
@property (assign,nonatomic) BOOL hasType4DueToTimerExpiryCount; 
@property (assign,nonatomic) unsigned long long type4DueToTimerExpiryCount;                         //@synthesize type4DueToTimerExpiryCount=_type4DueToTimerExpiryCount - In the implementation block
@property (nonatomic,retain) NSMutableArray * wci2Counters;                                         //@synthesize wci2Counters=_wci2Counters - In the implementation block
+(Class)wci2CountersType;
-(void)setHasLteTxPowerLimitCount:(BOOL)arg1 ;
-(unsigned long long)timestamp;
-(void)setHasTimeSharingWLANTimeInMS:(BOOL)arg1 ;
-(unsigned long long)wlanProtectionFramesDueToLTECoexCount;
-(void)addWci2Counters:(id)arg1 ;
-(BOOL)hasType4HonouredTimeInMS;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(unsigned long long)lteTxPowerLimitCount;
-(void)dealloc;
-(unsigned long long)type4HonouredTimeInMS;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimeSharingWLANIntervalCount:(unsigned long long)arg1 ;
-(BOOL)hasWlanRxPriTimeInMS;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)hasWlanRxPriCount;
-(void)setWlanRxPriTimeInMS:(unsigned long long)arg1 ;
-(BOOL)hasLteTxPowerLimitCount;
-(void)setHasLteTxPowerLimitTimeInMS:(BOOL)arg1 ;
-(void)setWlanProtectionFramesDueToLTECoexCount:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setTimeSharingWLANTimeInMS:(unsigned long long)arg1 ;
-(void)setWci2Counters:(NSMutableArray *)arg1 ;
-(unsigned long long)wlanRxPriCount;
-(id)wci2CountersAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)type4DueToTimerExpiryCount;
-(unsigned long long)hash;
-(unsigned long long)wci2CountersCount;
-(NSMutableArray *)wci2Counters;
-(BOOL)hasLteTxPowerLimitTimeInMS;
-(unsigned long long)type4HonouredCount;
-(void)setLteTxPowerLimitCount:(unsigned long long)arg1 ;
-(void)setHasWlanProtectionFramesDueToLTECoexCount:(BOOL)arg1 ;
-(id)description;
-(BOOL)hasType4HonouredCount;
-(void)setHasType4DueToTimerExpiryCount:(BOOL)arg1 ;
-(void)setType4DueToTimerExpiryCount:(unsigned long long)arg1 ;
-(void)setHasType4HonouredCount:(BOOL)arg1 ;
-(void)copyTo:(id)arg1 ;
-(unsigned long long)timeSharingWLANTimeInMS;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(void)setWlanRxPriCount:(unsigned long long)arg1 ;
-(BOOL)hasTimestamp;
-(void)clearWci2Counters;
-(void)setHasWlanRxPriTimeInMS:(BOOL)arg1 ;
-(void)setHasWlanRxPriCount:(BOOL)arg1 ;
-(void)setHasType4HonouredTimeInMS:(BOOL)arg1 ;
-(void)setLteTxPowerLimitTimeInMS:(unsigned long long)arg1 ;
-(void)setType4HonouredTimeInMS:(unsigned long long)arg1 ;
-(void)setHasTimeSharingWLANIntervalCount:(BOOL)arg1 ;
-(unsigned long long)timeSharingWLANIntervalCount;
-(BOOL)hasWlanProtectionFramesDueToLTECoexCount;
-(unsigned long long)wlanRxPriTimeInMS;
-(unsigned long long)lteTxPowerLimitTimeInMS;
-(BOOL)hasTimeSharingWLANTimeInMS;
-(BOOL)hasTimeSharingWLANIntervalCount;
-(void)writeTo:(id)arg1 ;
-(BOOL)hasType4DueToTimerExpiryCount;
-(void)setType4HonouredCount:(unsigned long long)arg1 ;
@end

