/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:40 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface AWDWiFiMetricRssiHistory : PBCodable <NSCopying> {

	SCD_Struct_AW15* _bcnFrmsHistorys;
	SCD_Struct_AW15* _bcnPerHistorys;
	SCD_Struct_AW15* _fwTxFrmsHistorys;
	SCD_Struct_AW15* _fwTxPerHistorys;
	SCD_Struct_AW15* _rssiHistorys;
	SCD_Struct_AW15* _txFrmsHistorys;
	SCD_Struct_AW15* _txPerHistorys;
	unsigned long long _timestamp;
	unsigned _gatewayARPHistory;
	SCD_Struct_AW3 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                            //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) unsigned long long rssiHistorysCount; 
@property (nonatomic,readonly) int* rssiHistorys; 
@property (nonatomic,readonly) unsigned long long txPerHistorysCount; 
@property (nonatomic,readonly) int* txPerHistorys; 
@property (nonatomic,readonly) unsigned long long txFrmsHistorysCount; 
@property (nonatomic,readonly) int* txFrmsHistorys; 
@property (nonatomic,readonly) unsigned long long fwTxPerHistorysCount; 
@property (nonatomic,readonly) int* fwTxPerHistorys; 
@property (nonatomic,readonly) unsigned long long fwTxFrmsHistorysCount; 
@property (nonatomic,readonly) int* fwTxFrmsHistorys; 
@property (nonatomic,readonly) unsigned long long bcnPerHistorysCount; 
@property (nonatomic,readonly) int* bcnPerHistorys; 
@property (nonatomic,readonly) unsigned long long bcnFrmsHistorysCount; 
@property (nonatomic,readonly) int* bcnFrmsHistorys; 
@property (assign,nonatomic) BOOL hasGatewayARPHistory; 
@property (assign,nonatomic) unsigned gatewayARPHistory;                              //@synthesize gatewayARPHistory=_gatewayARPHistory - In the implementation block
-(void)clearTxPerHistorys;
-(void)addRssiHistory:(int)arg1 ;
-(void)setBcnFrmsHistorys:(int*)arg1 count:(unsigned long long)arg2 ;
-(unsigned long long)timestamp;
-(unsigned)gatewayARPHistory;
-(void)addTxFrmsHistory:(int)arg1 ;
-(int)fwTxPerHistoryAtIndex:(unsigned long long)arg1 ;
-(void)clearTxFrmsHistorys;
-(int*)fwTxPerHistorys;
-(void)setFwTxPerHistorys:(int*)arg1 count:(unsigned long long)arg2 ;
-(int*)txPerHistorys;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setHasGatewayARPHistory:(BOOL)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setFwTxFrmsHistorys:(int*)arg1 count:(unsigned long long)arg2 ;
-(void)clearFwTxFrmsHistorys;
-(void)dealloc;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(int)fwTxFrmsHistoryAtIndex:(unsigned long long)arg1 ;
-(void)clearRssiHistorys;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)clearFwTxPerHistorys;
-(int*)bcnFrmsHistorys;
-(void)clearBcnFrmsHistorys;
-(unsigned long long)hash;
-(void)setRssiHistorys:(int*)arg1 count:(unsigned long long)arg2 ;
-(void)addBcnFrmsHistory:(int)arg1 ;
-(int)bcnPerHistoryAtIndex:(unsigned long long)arg1 ;
-(id)description;
-(int*)fwTxFrmsHistorys;
-(int)txFrmsHistoryAtIndex:(unsigned long long)arg1 ;
-(void)setGatewayARPHistory:(unsigned)arg1 ;
-(void)setTxPerHistorys:(int*)arg1 count:(unsigned long long)arg2 ;
-(unsigned long long)bcnPerHistorysCount;
-(unsigned long long)fwTxPerHistorysCount;
-(void)copyTo:(id)arg1 ;
-(BOOL)hasGatewayARPHistory;
-(void)addBcnPerHistory:(int)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(void)setBcnPerHistorys:(int*)arg1 count:(unsigned long long)arg2 ;
-(id)dictionaryRepresentation;
-(void)addTxPerHistory:(int)arg1 ;
-(BOOL)hasTimestamp;
-(int*)bcnPerHistorys;
-(int*)txFrmsHistorys;
-(unsigned long long)bcnFrmsHistorysCount;
-(unsigned long long)fwTxFrmsHistorysCount;
-(void)addFwTxPerHistory:(int)arg1 ;
-(unsigned long long)txPerHistorysCount;
-(void)addFwTxFrmsHistory:(int)arg1 ;
-(int)txPerHistoryAtIndex:(unsigned long long)arg1 ;
-(void)clearBcnPerHistorys;
-(void)writeTo:(id)arg1 ;
-(unsigned long long)rssiHistorysCount;
-(void)setTxFrmsHistorys:(int*)arg1 count:(unsigned long long)arg2 ;
-(int*)rssiHistorys;
-(int)bcnFrmsHistoryAtIndex:(unsigned long long)arg1 ;
-(int)rssiHistoryAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)txFrmsHistorysCount;
@end

