/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:41 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class AWDWiFiMetricsManagerBTCoexModeChange, AWDWiFiMetricsManagerBTCoexStats, AWDWiFiMetricsManagerChipCounters, NSMutableArray;

@interface AWDWiFiMetricsManagerOneStatsAssociationInfo : PBCodable <NSCopying> {

	unsigned long long _timestamp;
	AWDWiFiMetricsManagerBTCoexModeChange* _btCoexModeChange;
	AWDWiFiMetricsManagerBTCoexStats* _btCoexStats;
	AWDWiFiMetricsManagerChipCounters* _chipCounters;
	NSMutableArray* _chipCountersPerSlices;
	SCD_Struct_AW5 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                                          //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL hasChipCounters; 
@property (nonatomic,retain) AWDWiFiMetricsManagerChipCounters * chipCounters;                      //@synthesize chipCounters=_chipCounters - In the implementation block
@property (nonatomic,readonly) BOOL hasBtCoexStats; 
@property (nonatomic,retain) AWDWiFiMetricsManagerBTCoexStats * btCoexStats;                        //@synthesize btCoexStats=_btCoexStats - In the implementation block
@property (nonatomic,readonly) BOOL hasBtCoexModeChange; 
@property (nonatomic,retain) AWDWiFiMetricsManagerBTCoexModeChange * btCoexModeChange;              //@synthesize btCoexModeChange=_btCoexModeChange - In the implementation block
@property (nonatomic,retain) NSMutableArray * chipCountersPerSlices;                                //@synthesize chipCountersPerSlices=_chipCountersPerSlices - In the implementation block
+(Class)chipCountersPerSliceType;
-(AWDWiFiMetricsManagerBTCoexModeChange *)btCoexModeChange;
-(unsigned long long)timestamp;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)dealloc;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)setBtCoexModeChange:(AWDWiFiMetricsManagerBTCoexModeChange *)arg1 ;
-(unsigned long long)hash;
-(void)addChipCountersPerSlice:(id)arg1 ;
-(BOOL)hasBtCoexModeChange;
-(BOOL)hasBtCoexStats;
-(AWDWiFiMetricsManagerChipCounters *)chipCounters;
-(id)description;
-(BOOL)hasChipCounters;
-(void)copyTo:(id)arg1 ;
-(NSMutableArray *)chipCountersPerSlices;
-(BOOL)isEqual:(id)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned long long)chipCountersPerSlicesCount;
-(AWDWiFiMetricsManagerBTCoexStats *)btCoexStats;
-(BOOL)hasTimestamp;
-(id)chipCountersPerSliceAtIndex:(unsigned long long)arg1 ;
-(void)setBtCoexStats:(AWDWiFiMetricsManagerBTCoexStats *)arg1 ;
-(void)clearChipCountersPerSlices;
-(void)setChipCounters:(AWDWiFiMetricsManagerChipCounters *)arg1 ;
-(void)setChipCountersPerSlices:(NSMutableArray *)arg1 ;
-(void)writeTo:(id)arg1 ;
@end

