/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:47 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libnfstorage.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnfstorage.dylib/NFStorageController.h>

@interface NFStorageControllerIcfExpress : NFStorageController
-(id)dbProtectionType;
-(id)name;
-(id)_deleteAllIcfExpressEntities;
-(id)fetchIcfExpressEntitiesWithError:(id*)arg1 ;
-(void)updateIcfExpressEntitiesWithConfig:(id)arg1 ;
-(void)deleteAllIcfExpressEntities;
@end

