/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:51:24 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libnetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libnetwork.dylib/libnetwork.dylib-Structs.h>
#import <libnetwork.dylib/NWConcrete_nw_endpoint.h>

@interface NWOSURLEndpoint : NWConcrete_nw_endpoint {

	CFURLRef url_ref;
	unsigned short port;
	char* url;
	char* scheme;
	char* hostname;
	char* path;
	char* sanitized_url;
	char url_hash[9];

}
-(const char*)hostname;
-(id)copyDictionary;
-(unsigned short)port;
-(void)dealloc;
-(BOOL)isEqualToEndpoint:(id)arg1 matchInterface:(BOOL)arg2 matchParent:(BOOL)arg3 ;
-(id)copyEndpoint;
-(unsigned)type;
-(unsigned long long)getHash;
-(const char*)domainForPolicy;
-(char*)createDescription:(BOOL)arg1 ;
@end

