/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:55:00 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libobjc.A.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CAAnimatableValue <NSObject>
@optional
-(id)CA_roundToIntegerFromValue:(id)arg1;
-(id)CA_interpolateValue:(id)arg1 byFraction:(float)arg2;
-(id)CA_addValue:(id)arg1 multipliedBy:(int)arg2;
-(double)CA_distanceToValue:(id)arg1;

@end

