/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:55:01 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libobjc.A.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct __CFString* CFStringRef;

typedef struct {
	char* field1;
	unsigned long long field2;
} SCD_Struct_NS2;

typedef struct sqlite3_stmt* sqlite3_stmtRef;

typedef struct __IOHIDEvent* IOHIDEventRef;

