/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:55:00 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libobjc.A.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libobjc.A.dylib/libobjc.A.dylib-Structs.h>
@interface Protocol : NSObject
-(objc_method_description*)descriptionForClassMethod:(SEL)arg1 ;
-(unsigned long long)hash;
-(objc_method_description*)descriptionForInstanceMethod:(SEL)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(BOOL)conformsTo:(id)arg1 ;
-(const char*)name;
@end

