/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:33:10 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libBKDM2.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <BiometricSupport/BiometricMatchOperation.h>

@interface BiometricMatchOperationPearl : BiometricMatchOperation {

	BOOL _longTimeout;
	BOOL _autoRetry;

}

@property (assign,nonatomic) BOOL longTimeout;              //@synthesize longTimeout=_longTimeout - In the implementation block
@property (assign,nonatomic) BOOL autoRetry;                //@synthesize autoRetry=_autoRetry - In the implementation block
-(void)setLongTimeout:(BOOL)arg1 ;
-(BOOL)longTimeout;
-(BOOL)autoRetry;
-(void)setAutoRetry:(BOOL)arg1 ;
@end

