/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:33:10 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libBKDM2.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <BiometricSupport/BiometricAutoBugCapture.h>

@interface PearlAutoBugCapture : BiometricAutoBugCapture
-(id)getTypeForReason:(unsigned long long)arg1 ;
-(BOOL)sendSignature:(id)arg1 withDuration:(double)arg2 ;
-(id)getSubtypeForReason:(unsigned long long)arg1 ;
@end

