/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:44 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libThreadExternalCommissioner.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSNetServiceBrowserDelegate.h>
#import <libobjc.A.dylib/NSNetServiceDelegate.h>

@protocol BorderAgentListener;
@class NSNetServiceBrowser, NSMutableArray, NSString;

@interface BorderAgentFinder : NSObject <NSNetServiceBrowserDelegate, NSNetServiceDelegate> {

	NSNetServiceBrowser* _browser;
	NSMutableArray* _borderAgents;
	id<BorderAgentListener> _delegate;

}

@property (__weak) id<BorderAgentListener> delegate;                //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)netServiceWillResolve:(id)arg1 ;
-(void)netServiceDidResolveAddress:(id)arg1 ;
-(void)netService:(id)arg1 didNotResolve:(id)arg2 ;
-(void)netServiceBrowser:(id)arg1 didRemoveService:(id)arg2 moreComing:(BOOL)arg3 ;
-(void)start;
-(unsigned long long)getNumberOfBorderAgents;
-(id)getBorderAgentAtIndex:(unsigned long long)arg1 ;
-(id)getAgentDescription:(unsigned long long)arg1 ;
-(void)netServiceBrowserWillSearch:(id)arg1 ;
-(void)setDelegate:(id<BorderAgentListener>)arg1 ;
-(void)netServiceBrowser:(id)arg1 didFindService:(id)arg2 moreComing:(BOOL)arg3 ;
-(void)netServiceBrowserDidStopSearch:(id)arg1 ;
-(void)stop;
-(id<BorderAgentListener>)delegate;
@end

