/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:45 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libThreadExternalCommissioner.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct shared_ptr<ot::commissioner::Commissioner> {
	Commissioner __ptr_;
	__shared_weak_count __cntrl_;
} shared_ptr<ot::commissioner::Commissioner>;

