/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 10:51:20 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/system/libdispatch.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface OS_object : NSObject
-(id)init;
-(void)_xref_dispose;
-(unsigned long long)retainCount;
-(BOOL)retainWeakReference;
-(BOOL)allowsWeakReference;
-(id)retain;
-(oneway void)release;
@end

