/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:47 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/libpartition2_dynamic.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface LPMedia : NSObject {

	unsigned _ioMedia;

}

@property (assign) unsigned ioMedia;              //@synthesize ioMedia=_ioMedia - In the implementation block
+(id)allMedia;
+(id)mediaForPath:(id)arg1 ;
+(id)mediaOfCorrectTypeGivenIOMedia:(unsigned)arg1 ;
+(id)mediaForPath:(id)arg1 snapshotName:(id*)arg2 ;
+(id)mediaForUUID:(id)arg1 ;
+(id)liveMediaForSnapshotAtPath:(id)arg1 ;
+(unsigned)_copyIOMediaForDiskWithPath:(id)arg1 ;
+(unsigned)_copyLiveFilesystemIOMediaForRootedSnapshot;
+(id)mediaForPath:(id)arg1 isSnapshot:(BOOL*)arg2 ;
+(id)snapshotNameForMediaForPath:(id)arg1 ;
+(id)supportedContentTypes;
+(id)mediaForBSDNameOrDeviceNode:(id)arg1 ;
+(id)contentTypeToSubclassMap;
-(id)content;
-(BOOL)isInternal;
-(id)BSDName;
-(unsigned)ioMedia;
-(void)dealloc;
-(BOOL)isWhole;
-(id)description;
-(BOOL)isEqual:(id)arg1 ;
-(id)name;
-(id)devNodePath;
-(id)getStringPropertyWithName:(id)arg1 ;
-(id)initWithIOMediaObject:(unsigned)arg1 ;
-(BOOL)getBoolPropertyWithName:(id)arg1 ;
-(void)setIoMedia:(unsigned)arg1 ;
-(BOOL)isInternalAndIsRootDevice:(BOOL*)arg1 ;
-(id)wholeMediaForMedia;
-(BOOL)setName:(id)arg1 withError:(id*)arg2 ;
-(id)mountPoint;
-(id)mediaUUID;
@end

