/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, March 2, 2021 at 11:32:49 AM US Time
* Operating System: Version 14.3 (Build 18C66)
* Image Source: /usr/lib/system/libsystem_blocks.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libsystem_blocks.dylib/libsystem_blocks.dylib-Structs.h>
#import <CoreFoundation/NSBlock.h>

@interface __NSGlobalBlock__ : NSBlock
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)_isDeallocating;
-(BOOL)_tryRetain;
-(unsigned long long)retainCount;
-(id)copy;
-(id)retain;
-(oneway void)release;
@end

